server:
  port: 8888
spring:
  application:
    name: base-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        #http://127.0.0.1:8888/abcddd1/get
        - id: service-hello2
          uri: http://httpbin.org/get
          predicates:
            - Path=/abcddd1/**
          filters:
            - StripPrefix=1
        #http://127.0.0.1:8888/abcddd/hi?name=forezp
        - id: service-hello
          uri: lb://service-helloworld
          predicates:
            - Path=/abcddd/**
          filters:
            - StripPrefix=1
#  boot:
#    admin:
#      client:
#        url: http://localhost:8788
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/