server:
  port: 8889
security:
  oauth2:
    resource:
      jwt:
        key-value: test-secret
spring:
  application:
    name: service-helloworld
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/base-cloud?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 20
      max-lifetime: 30000
      idle-timeout: 30000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 500
        prepStmtCacheSqlLimit: 4096
        useServerPrepStmts: true
    redis: # redis的配置
      hostName: redis.url
      port: 6379   # 字典表的redis
      password:
      timeout: 10000
      pool:
        maxTotal: 100 # 可用连接实例的最大数目，默认值为8
        maxIdle: 100  # 控制一个pool最多有多少个状态为idle(空闲的)的jedis实例，默认值也是8
        minIdle: 8 # 初始化连接数
        maxWaitMillis: 10000   # 当池内没有返回对象时，最大等待时间
        testWhileIdle: true    # 向调用者输出“链接”对象时，是否检测它的空闲超时；
        testOnBorrow: true     # 当调用borrow Object方法时，是否进行有效性检查
        testOnReturn: true     # 当调用return Object方法时，是否进行有效性检查
        numTestsPerEvictionRun: 8 # 对于“空闲链接”检测线程而言，每次检测的链接资源的个数。默认为3.
        timeBetweenEvictionRunsMillis: 30000  # “空闲链接”检测线程，检测的周期，毫秒数。如果为负值，表示不运行“检测线程”。默认为-1.
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/